package resource

import (
	"context"
	"fmt"

	"terraform-provider-plural/internal/client"
	"terraform-provider-plural/internal/common"
	"terraform-provider-plural/internal/model"

	"github.com/hashicorp/terraform-plugin-framework-validators/objectvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	gqlclient "github.com/pluralsh/console/go/client"
)

var _ resource.Resource = &MonitorResource{}
var _ resource.ResourceWithImportState = &MonitorResource{}

func NewMonitorResource() resource.Resource {
	return &MonitorResource{}
}

type MonitorResource struct {
	client *client.Client
}

func (r *MonitorResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_monitor"
}

func (r *MonitorResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Monitor resource. A monitor periodically evaluates a log or metrics query of a service deployment " +
			"against a threshold and fires alerts when it is crossed. When attached to a workbench, it can also start " +
			"a workbench investigation when it fires.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description:         "Internal identifier of this monitor.",
				MarkdownDescription: "Internal identifier of this monitor.",
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"name": schema.StringAttribute{
				Description:         "Short name used to identify this monitor.",
				MarkdownDescription: "Short name used to identify this monitor.",
				Required:            true,
				Validators:          []validator.String{stringvalidator.LengthAtLeast(1)},
			},
			"service_id": schema.StringAttribute{
				Description:         "ID of the service deployment this monitor is attached to.",
				MarkdownDescription: "ID of the service deployment this monitor is attached to.",
				Required:            true,
			},
			"workbench_id": schema.StringAttribute{
				Description:         "ID of the workbench this monitor is attached to. When set, the monitor can start a workbench investigation when it fires. It is required if the query uses a named workbench tool.",
				MarkdownDescription: "ID of the workbench this monitor is attached to. When set, the monitor can start a workbench investigation when it fires. It is required if the query uses a named workbench tool.",
				Optional:            true,
			},
			"prompt": schema.StringAttribute{
				Description:         "Prompt used when the monitor starts a workbench investigation.",
				MarkdownDescription: "Prompt used when the monitor starts a workbench investigation.",
				Optional:            true,
				Validators:          []validator.String{stringvalidator.LengthAtLeast(1)},
			},
			"modes": workbenchJobModesSchema("Mode-specific options for workbench jobs started by this monitor."),
			"description": schema.StringAttribute{
				Description:         "Description of what this monitor is checking.",
				MarkdownDescription: "Description of what this monitor is checking.",
				Optional:            true,
				Validators:          []validator.String{stringvalidator.LengthAtLeast(1)},
			},
			"alert_template": schema.StringAttribute{
				Description:         "Template used when rendering alert messages for this monitor.",
				MarkdownDescription: "Template used when rendering alert messages for this monitor.",
				Optional:            true,
				Validators:          []validator.String{stringvalidator.LengthAtLeast(1)},
			},
			"severity": schema.StringAttribute{
				Description:         withAllowedValues("Severity level applied to alerts generated by this monitor.", enumValues(gqlclient.AllAlertSeverity), false),
				MarkdownDescription: withAllowedValues("Severity level applied to alerts generated by this monitor.", enumValues(gqlclient.AllAlertSeverity), true),
				Required:            true,
				Validators:          []validator.String{stringvalidator.OneOf(enumValues(gqlclient.AllAlertSeverity)...)},
			},
			"type": schema.StringAttribute{
				Description:         withAllowedValues("Monitor data type. It has to match the query, i.e. LOG requires query.log and METRICS requires query.metrics.", enumValues(gqlclient.AllMonitorType), false),
				MarkdownDescription: withAllowedValues("Monitor data type. It has to match the query, i.e. `LOG` requires `query.log` and `METRICS` requires `query.metrics`.", enumValues(gqlclient.AllMonitorType), true),
				Required:            true,
				Validators:          []validator.String{stringvalidator.OneOf(enumValues(gqlclient.AllMonitorType)...)},
			},
			"evaluation_cron": schema.StringAttribute{
				Description:         "Cron schedule defining when the monitor is evaluated, e.g. */5 * * * *.",
				MarkdownDescription: "Cron schedule defining when the monitor is evaluated, e.g. `*/5 * * * *`.",
				Required:            true,
				Validators:          []validator.String{stringvalidator.LengthAtLeast(1)},
			},
			"query": schema.SingleNestedAttribute{
				Description:         "Query used to fetch data for this monitor. Exactly one of log or metrics has to be set.",
				MarkdownDescription: "Query used to fetch data for this monitor. Exactly one of `log` or `metrics` has to be set.",
				Required:            true,
				Attributes: map[string]schema.Attribute{
					"log": schema.SingleNestedAttribute{
						Description:         "Log query used when the monitor type is LOG.",
						MarkdownDescription: "Log query used when the monitor type is `LOG`.",
						Optional:            true,
						Validators: []validator.Object{
							objectvalidator.ExactlyOneOf(path.MatchRelative().AtParent().AtName("metrics")),
						},
						Attributes: map[string]schema.Attribute{
							"tool": schema.StringAttribute{
								Description:         "Name of the workbench logs tool. When not set, the native Plural logs provider is used.",
								MarkdownDescription: "Name of the workbench logs tool. When not set, the native Plural logs provider is used.",
								Optional:            true,
								Validators:          []validator.String{stringvalidator.LengthAtLeast(1)},
							},
							"query": schema.StringAttribute{
								Description:         "Log query string passed to the underlying log provider.",
								MarkdownDescription: "Log query string passed to the underlying log provider.",
								Required:            true,
							},
							"bucket_size": schema.StringAttribute{
								Description:         "Time bucket size used when aggregating log results, e.g. 5m.",
								MarkdownDescription: "Time bucket size used when aggregating log results, e.g. `5m`.",
								Required:            true,
							},
							"duration": schema.StringAttribute{
								Description:         "Lookback duration for the log query, e.g. 1h.",
								MarkdownDescription: "Lookback duration for the log query, e.g. `1h`.",
								Optional:            true,
								Validators:          []validator.String{stringvalidator.LengthAtLeast(1)},
							},
							"operator": schema.StringAttribute{
								Description:         withAllowedValues("Operator used when combining multiple log queries. Defaults to OR.", enumValues(gqlclient.AllMonitorOperator), false),
								MarkdownDescription: withAllowedValues("Operator used when combining multiple log queries. Defaults to `OR`.", enumValues(gqlclient.AllMonitorOperator), true),
								Optional:            true,
								Computed:            true,
								Default:             stringdefault.StaticString(string(gqlclient.MonitorOperatorOr)),
								Validators:          []validator.String{stringvalidator.OneOf(enumValues(gqlclient.AllMonitorOperator)...)},
							},
							"facets": schema.ListNestedAttribute{
								Description:         "Key/value facets applied as additional filters on the log query.",
								MarkdownDescription: "Key/value facets applied as additional filters on the log query.",
								Optional:            true,
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"key": schema.StringAttribute{
											Description:         "Facet key, e.g. a Kubernetes namespace or pod label name.",
											MarkdownDescription: "Facet key, e.g. a Kubernetes namespace or pod label name.",
											Required:            true,
										},
										"value": schema.StringAttribute{
											Description:         "Facet value to match for the given key.",
											MarkdownDescription: "Facet value to match for the given key.",
											Required:            true,
										},
									},
								},
							},
							"options": schema.SingleNestedAttribute{
								Description:         "Provider-specific log query options.",
								MarkdownDescription: "Provider-specific log query options.",
								Optional:            true,
								Attributes: map[string]schema.Attribute{
									"azure": schema.SingleNestedAttribute{
										Description:         "Azure log query options.",
										MarkdownDescription: "Azure log query options.",
										Optional:            true,
										Attributes: map[string]schema.Attribute{
											"resource_id": schema.StringAttribute{
												Description:         "Azure resource ID to query logs for.",
												MarkdownDescription: "Azure resource ID to query logs for.",
												Optional:            true,
											},
										},
									},
								},
							},
						},
					},
					"metrics": schema.SingleNestedAttribute{
						Description:         "Metrics query used when the monitor type is METRICS.",
						MarkdownDescription: "Metrics query used when the monitor type is `METRICS`.",
						Optional:            true,
						Attributes: map[string]schema.Attribute{
							"tool": schema.StringAttribute{
								Description:         "Name of the workbench metrics tool. When not set, the native Plural metrics provider is used.",
								MarkdownDescription: "Name of the workbench metrics tool. When not set, the native Plural metrics provider is used.",
								Optional:            true,
								Validators:          []validator.String{stringvalidator.LengthAtLeast(1)},
							},
							"query": schema.StringAttribute{
								Description:         "Metrics query string passed to the underlying metrics provider.",
								MarkdownDescription: "Metrics query string passed to the underlying metrics provider.",
								Required:            true,
							},
							"step": schema.StringAttribute{
								Description:         "Metrics query step, e.g. 5m.",
								MarkdownDescription: "Metrics query step, e.g. `5m`.",
								Optional:            true,
								Validators:          []validator.String{stringvalidator.LengthAtLeast(1)},
							},
							"duration": schema.StringAttribute{
								Description:         "Lookback duration for the metrics query, e.g. 1h.",
								MarkdownDescription: "Lookback duration for the metrics query, e.g. `1h`.",
								Optional:            true,
								Validators:          []validator.String{stringvalidator.LengthAtLeast(1)},
							},
							"options": schema.SingleNestedAttribute{
								Description:         "Provider-specific metrics query options.",
								MarkdownDescription: "Provider-specific metrics query options.",
								Optional:            true,
								Attributes: map[string]schema.Attribute{
									"azure": schema.SingleNestedAttribute{
										Description:         "Azure metrics query options.",
										MarkdownDescription: "Azure metrics query options.",
										Optional:            true,
										Attributes: map[string]schema.Attribute{
											"resource_id":       azureMetricsOptionAttribute("Azure resource ID to query metrics for."),
											"metrics_namespace": azureMetricsOptionAttribute("Azure metrics namespace."),
											"aggregation":       azureMetricsOptionAttribute("Azure metrics aggregation type."),
											"filter":            azureMetricsOptionAttribute("Azure metrics filter expression."),
											"order_by":          azureMetricsOptionAttribute("Azure metrics ordering expression."),
											"roll_up_by":        azureMetricsOptionAttribute("Azure metrics dimension to roll up by."),
											"metrics_endpoint":  azureMetricsOptionAttribute("Azure metrics endpoint override."),
										},
									},
								},
							},
						},
					},
				},
			},
			"threshold": schema.SingleNestedAttribute{
				Description:         "Threshold that determines when the monitor fires.",
				MarkdownDescription: "Threshold that determines when the monitor fires.",
				Required:            true,
				Attributes: map[string]schema.Attribute{
					"aggregate": schema.StringAttribute{
						Description:         withAllowedValues("Aggregation function applied over the result set.", enumValues(gqlclient.AllMonitorAggregate), false),
						MarkdownDescription: withAllowedValues("Aggregation function applied over the result set.", enumValues(gqlclient.AllMonitorAggregate), true),
						Required:            true,
						Validators:          []validator.String{stringvalidator.OneOf(enumValues(gqlclient.AllMonitorAggregate)...)},
					},
					"value": schema.Float64Attribute{
						Description:         "Value the aggregated result has to cross to fire the alert.",
						MarkdownDescription: "Value the aggregated result has to cross to fire the alert.",
						Required:            true,
					},
				},
			},
		},
	}
}

func azureMetricsOptionAttribute(description string) schema.StringAttribute {
	return schema.StringAttribute{
		Description:         description,
		MarkdownDescription: description,
		Optional:            true,
	}
}

func (r *MonitorResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	data, ok := req.ProviderData.(*common.ProviderData)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Monitor Resource Configure Type",
			fmt.Sprintf("Expected *common.ProviderData, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.client = data.Client
}

func (r *MonitorResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	data := new(model.Monitor)
	resp.Diagnostics.Append(req.Plan.Get(ctx, data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	attrs := data.Attributes(ctx, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	response, err := r.client.CreateMonitor(ctx, attrs)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create monitor, got error: %s", err))
		return
	}

	data.From(response.CreateMonitor, ctx, &resp.Diagnostics)
	resp.Diagnostics.Append(resp.State.Set(ctx, data)...)
}

func (r *MonitorResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	data := new(model.Monitor)
	resp.Diagnostics.Append(req.State.Get(ctx, data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	response, err := r.client.GetMonitor(ctx, data.Id.ValueString())
	if err != nil && !client.IsNotFound(err) {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to get monitor, got error: %s", err))
		return
	}
	if response == nil || response.Monitor == nil || client.IsNotFound(err) {
		resp.State.RemoveResource(ctx)
		return
	}

	data.From(response.Monitor, ctx, &resp.Diagnostics)
	resp.Diagnostics.Append(resp.State.Set(ctx, data)...)
}

func (r *MonitorResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	data := new(model.Monitor)
	resp.Diagnostics.Append(req.Plan.Get(ctx, data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	attrs := data.Attributes(ctx, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	_, err := r.client.UpdateMonitor(ctx, data.Id.ValueString(), attrs)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update monitor, got error: %s", err))
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, data)...)
}

func (r *MonitorResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	data := new(model.Monitor)
	resp.Diagnostics.Append(req.State.Get(ctx, data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if _, err := r.client.DeleteMonitor(ctx, data.Id.ValueString()); err != nil && !client.IsNotFound(err) {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete monitor, got error: %s", err))
		return
	}
}

func (r *MonitorResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
